stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.8
  script:
    - pip install flake8
    - flake8 src/
  only:
    - merge_requests
  allow_failure: true

dvc_pull:
  stage: test
  image: python:3.8
  script:
    - pip install dvc
    - dvc pull
  only:
    - merge_requests

test:
  stage: test
  image: python:3.8
  script:
    - pip install pytest
    - pytest tests/
    - pip install requests
    - pytest tests/test_api.py
  only:
    - merge_requests
